#!/bin/sh
testCases=""
testCases="$testCases addressing"
testCases="$testCases binary2"
testCases="$testCases binary256"
testCases="$testCases binary300"
testCases="$testCases binary512"
testCases="$testCases binary600"
testCases="$testCases binary8000"
testCases="$testCases data"
testCases="$testCases equ"
testCases="$testCases mml"
testCases="$testCases numparse"
testCases="$testCases rel"
testCases="$testCases segment"

cmd=$1
for testCase in $testCases; do
	jrasm -d test-$testCase.asm > result/test-$testCase.result.txt
	if [ "$cmd" == "update" ] ; then
		echo "update: $testCase"
		cp result/test-$testCase.result.txt result/test-$testCase.expect.txt
	else
		echo "$testCase"
		diff -u result/test-$testCase.expect.txt result/test-$testCase.result.txt
	fi
done
