#!/bin/sh
caseNames=""
caseNames="$caseNames addressing"
caseNames="$caseNames all-instruction"
caseNames="$caseNames binary2"
caseNames="$caseNames binary256"
caseNames="$caseNames binary300"
caseNames="$caseNames binary512"
caseNames="$caseNames binary600"
caseNames="$caseNames binary8000"
caseNames="$caseNames data"
caseNames="$caseNames equ"
caseNames="$caseNames hexdump"
caseNames="$caseNames literal"
caseNames="$caseNames mml"
caseNames="$caseNames rel"
caseNames="$caseNames segment"

#if [ $# = 1 ] ; then
#	caseName=$1
#	cmd=""
#elif [ $# = 2 ] ; then
#	caseName=$1
#	cmd=$2
#else
#	echo usage: tester [all|casename] update?
#fi
cmd=$1
for caseName in $caseNames; do
	jrasm -d -l test-$caseName.asm > result/test-$caseName.result.txt
	if [ "$cmd" = "update" ] ; then
		echo "update: $caseName"
		cp result/test-$caseName.result.txt result/test-$caseName.expect.txt
	else
		echo "$caseName"
		diff -u result/test-$caseName.expect.txt result/test-$caseName.result.txt
	fi
done
