	.org	0x1000

	.db	m"CDEFGAB"
	.db	m"O1 CDEFGAB", m"O2 CDEFGAB", m"O3 CDEFGAB", m"O4 CDEFGAB", m"O5 CDEFGAB"
	.db	m"O3 C1D2.C2D4.C4D8.C8D16.C16"
	.db	m"R1R2.R2R4.R4R8.R8R16.R16"
	.db	m"O1 CC+DD+EFF+GG+AA+B"
	.db	m"O2 CC+DD+EFF+GG+AA+B"
	.db	m"O3 CC+DD+EFF+GG+AA+B"
	.db	m"O4 CC+DD+EFF+GG+AA+B"
	.db	m"O5 CC+DD+EFF+GG+AA+B"
	.db	m"O1 CC+DD+EFF+GG+AA+B"
	.db	m"> CC+DD+EFF+GG+AA+B"
	.db	m"> CC+DD+EFF+GG+AA+B"
	.db	m"> CC+DD+EFF+GG+AA+B"
	.db	m"> CC+DD+EFF+GG+AA+B;"
	.db	m"O5 BA+AG+GF+FED+DC+C"
	.db	m"< BA+AG+GF+FED+DC+C"
	.db	m"< BA+AG+GF+FED+DC+C"
	.db	m"< BA+AG+GF+FED+DC+C"
	.db	m"< BA+AG+GF+FED+DC+C;"
	.db	m"CDEFGAB;"
	.db	m"O1 CDEFGAB;"
	.db	m"CDEFGAB"
	.db	m"O1 CDEFGAB;"
	.db	m"CDEFGAB"
	.db	m"L1 CDE R FG"
	.db	m"L2. CDE R FG", m"L2 CDE R FG"
	.db	m"L4. CDE R FG", m"L4 CDE R FG"
	.db	m"L8. CDE R FG", m"L8 CDE R FG"
	.db	m"L16. CDE R FG", m"L16 CDE R FG"
	.db	m"CCCC", m"CCCC"
	.db	m"CCCC"
	.db	m"CCCC;"
	.db	m"CCCC"
