	.org	0x1000

	.mml	"CDEFGAB"
	.mml	"O1 CDEFGAB", "O2 CDEFGAB", "O3 CDEFGAB", "O4 CDEFGAB", "O5 CDEFGAB"
	.mml	"O3 C1C2.C2C4.C4C8.C8C16.C16"
	.mml	"R1R2.R2R4.R4R8.R8R16.R16"
	.mml	"O1 CC+DD+EFF+GG+AA+B"
	.mml	"O2 CC+DD+EFF+GG+AA+B"
	.mml	"O3 CC+DD+EFF+GG+AA+B"
	.mml	"O4 CC+DD+EFF+GG+AA+B"
	.mml	"O5 CC+DD+EFF+GG+AA+B"
	.mml	"O1 CC+DD+EFF+GG+AA+B"
	.mml	"> CC+DD+EFF+GG+AA+B"
	.mml	"> CC+DD+EFF+GG+AA+B"
	.mml	"> CC+DD+EFF+GG+AA+B"
	.mml	"> CC+DD+EFF+GG+AA+B"
	.mml	"O5 BA+AG+GF+FED+DC+C"
	.mml	"< BA+AG+GF+FED+DC+C"
	.mml	"< BA+AG+GF+FED+DC+C"
	.mml	"< BA+AG+GF+FED+DC+C"
	.mml	"< BA+AG+GF+FED+DC+C"
	.mml	"CDEFGAB;"
	.mml	"O1 CDEFGAB;"
	.mml	"CDEFGAB"
	.mml	"O1 CDEFGAB;"
	.mml	"CDEFGAB"
